version: '2'

services:
  twink-server:
    image: ghcr.io/barabum0/twink-iot:latest
    restart: unless-stopped
    expose:
      - 8083

    environment:
      GYVERTWINK__IP: 192.168.1.36

  frpc:
    image: snowdreamtech/frpc:0.60
    restart: unless-stopped

    volumes:
      - "./frpc.toml:/etc/frp/frpc.toml"
